# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver

replicaCount: 1

image:
  repository: abdqadr/eurekaserver
  tag: latest

containerPort: 8761

service:
  type: LoadBalancer
  port: 8761
  targetPort: 8761

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: false
keycloak_enabled: false