server:
  port: 8085
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: qadr_mongodb
      port: 27017
      host: localhost
#      uri: mongodb://localhost:27017/qadr
  application:
    name: customer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      netflix:
          eureka: OFF
          discovery: OFF
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
