server:
  port: 8085
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1
  application:
    name: customer
  config:
    fail-fast: true
    import: configserver:http://localhost:9090/
#  data:
#    mongodb:
#      authentication-database: admin
#      username: root
#      password: example
#      database: qadr_mongodb
#      port: 27017
#      host: localhost
#      uri: mongodb://localhost:27017/qadr

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#logging:
#  level:
#    com:
#      netflix:
#          eureka: OFF
#          discovery: OFF
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
