# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: gateway-deployment
deploymentLabel: gateway

replicaCount: 1

image:
  repository: abdqadr/gateway
  tag: latest

containerPort: 9001

service:
  type: LoadBalancer
  port: 9001
  targetPort: 9001

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: true