version: "3.8"
services:
  zipkin:
     image: openzipkin/zipkin
     restart: always
     ports:
       - "9410:9410"
       - "9411:9411"
     networks:
       - qadr_network
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - qadr_network
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - qadr_network
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - qadr_network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
  configserver:
    image: abdqadr/configserver:latest
    restart: always
    ports:
      - "9111:9111"
    networks:
      - qadr_network

  eurekaserver:
    image: abdqadr/eureka-server:latest
    restart: always
    ports:
      - "8761:8761"
    networks:
      - qadr_network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 10s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: http://configserver:9111/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/hekl
  gateway:
    image: abdqadr/gateway:latest
    restart: always
    ports:
      - "9001:9001"
    networks:
      - qadr_network
    depends_on:
      - configserver
      - keycloak
      - zipkin
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 7
        window: 300s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: http://configserver:9111/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
  customer:
    image: abdqadr/customer:latest
    restart: always
    ports:
      - "8085:8085"
    networks:
      - qadr_network
    depends_on:
      - mongodb
      - eurekaserver
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:9111/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
  openfeign:
    image: abdqadr/openfeign:latest
    restart: always
    ports:
      - "8087:8087"
    networks:
      - qadr_network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 30s
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:9111/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27107"
    networks:
      - qadr_network
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    networks:
#      - qadr_network
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  data: {}
networks:
  qadr_network: