version: "3.9"
services:
  eurekaserver:
    image: abdqadr/eureka-server:1.0
    restart: always
    ports:
      - "8761:8761"
    networks:
      - qadr_network
  configserver:
    image: abdqadr/configserver:1.0
    restart: always
    ports:
      - "9090:9090"
    networks:
      - qadr_network
#    environment:
#      SPRING_PROFILES_ACTIVE: native
#      CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS: classpath:/config
  customer:
    image: abdqadr/customer:latest
    restart: always
    ports:
      - "8085:8085"
    networks:
      - qadr_network
    depends_on:
      - mongodb
      - eurekaserver
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:9090/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: example
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27107"
    networks:
      - qadr_network
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - qadr_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  data: {}
networks:
  qadr_network: