global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'customer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer:8085']
  - job_name: 'openfeign'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['openfeign:8087']