# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: customer-deployment
deploymentLabel: customer

replicaCount: 1

image:
  repository: abdqadr/customer
  tag: latest

containerPort: 8085

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true