# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: openfeign-deployment
deploymentLabel: openfeign

replicaCount: 1

image:
  repository: abdqadr/openfeign
  tag: latest

containerPort: 8087

service:
  type: LoadBalancer
  port: 8087
  targetPort: 8087

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false