spring:
  application:
    environment: production
    config:
      type: classpath
    name: eurekaserver
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF