server:
  port: 8087
spring:
  application:
    environment: production
    config:
      type: classpath
    name: openfeign
feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      CustomerClient:
        minimumNumberOfCalls: 3
  timelimiter:
    instances:
      CustomerClient:
        timeoutDuration: 10s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
