server:
  port: 8000
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    default: debug
    com:
      netflix:
        eureka: OFF
        discovery: OFF
