server:
  port: 8087
spring:
  application:
    name: openfeign
  config:
    fail-fast: true
    import: configserver:http://localhost:9090/
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  ratelimiter:
    instances:
      rateIt:
        timeoutDuration: 5000
        limitForPeriod: 1
        limitRefreshPeriod: 5000
    configs:
      default:
        registerHealthIndicator: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
