server:
  port: 8087
spring:
  application:
    name: openfeign
  config:
    fail-fast: true
    import: configserver:http://localhost:9090/
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
