server:
  port: 8087
spring:
  application:
    name: open-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
