apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfeign-deployment
  labels:
    app: openfeign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfeign
  template:
    metadata:
      labels:
        app: openfeign
    spec:
      containers:
        - name: openfeign
          image: abdqadr/openfeign:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: openfeign-service
spec:
  selector:
    app: openfeign
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087