spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1
  application:
    name: eurekaserver
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF